version: '3.8'

services:
  dream:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8123:8123"
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
